"use client";

import Link from "next/link";

export default function PrivacyPolicy() {
    return (
        <div className="min-h-screen relative z-10">
            <div className="max-w-3xl mx-auto px-6 py-12 lg:px-8">
                {/* Header */}
                <div className="mb-10">
                    <Link
                        href="/"
                        className="text-sm text-slate-500 hover:text-slate-700 transition-colors flex items-center gap-1.5 mb-6"
                    >
                        <span>←</span> Back to Locus
                    </Link>
                    <h1 className="text-4xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-cyan-500 mb-2">
                        Privacy Policy
                    </h1>
                    <p className="text-slate-500 text-sm">
                        Last updated: March 7, 2026 · Effective immediately
                    </p>
                </div>

                <div className="space-y-8">
                    {/* Overview */}
                    <Section title="1. Overview">
                        <p>
                            Locus (&quot;the Platform&quot;) is an AI-powered geospatial intelligence system developed
                            by <strong>Intsemble</strong>. This Privacy Policy explains how we collect, use, and protect
                            information when you use our location analysis services.
                        </p>
                    </Section>

                    {/* Data Collection */}
                    <Section title="2. Information We Process">
                        <p>When you use Locus, we process the following data:</p>
                        <ul className="list-disc list-inside space-y-1.5 mt-3 text-slate-600">
                            <li><strong>Query Data</strong> — Business type, target location, and any additional context you provide in the chat interface.</li>
                            <li><strong>Geospatial Data</strong> — Location coordinates, competitor positions and geographic parameters retrieved through the Google Places API and Google Maps Platform.</li>
                            <li><strong>Analysis Outputs</strong> — Market research findings, competitor analysis, gap analysis computations, and strategic synthesis reports generated by our multi-agent AI system.</li>
                            <li><strong>Session Data</strong> — Temporary session identifiers required for pipeline state management during an active analysis.</li>
                        </ul>
                    </Section>

                    {/* Google Maps */}
                    <Section title="3. Google Maps Platform">
                        <div className="bg-blue-50/60 border border-blue-100 rounded-xl p-4 mb-4">
                            <p className="text-blue-800 text-sm font-medium mb-2">📍 Google Maps Platform Notice</p>
                            <p className="text-blue-700 text-sm leading-relaxed">
                                Locus utilizes the Google Maps Platform, including the Google Maps Static API and Google Places API.
                                By using Locus, you acknowledge and agree to be bound by the{" "}
                                <a
                                    href="https://maps.google.com/help/terms_maps/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="underline font-medium hover:text-blue-900"
                                >
                                    Google Maps/Google Earth Additional Terms of Service
                                </a>{" "}
                                and the{" "}
                                <a
                                    href="https://policies.google.com/privacy"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="underline font-medium hover:text-blue-900"
                                >
                                    Google Privacy Policy
                                </a>.
                            </p>
                        </div>
                        <p>
                            Geospatial data displayed through map visualizations is provided by Google and is subject to
                            Google&apos;s own data handling and privacy practices. Locus does not independently store or
                            redistribute raw Google Maps data beyond the scope of a single user session.
                        </p>
                    </Section>

                    {/* AI Processing */}
                    <Section title="4. AI Data Processing">
                        <p>
                            Locus employs a multi-agent AI pipeline powered by Google Vertex AI and the Gemini family of models.
                            Your queries and the resulting analysis are processed through Google Cloud infrastructure.
                            Intsemble does not use your query data to train or fine-tune any AI models. Analysis results are
                            generated in real-time and are not persisted beyond your active session unless you explicitly
                            download a report.
                        </p>
                    </Section>

                    {/* Data Retention */}
                    <Section title="5. Data Retention">
                        <p>
                            Locus operates on a <strong>zero-retention model</strong> for user query data. Session state
                            is maintained only for the duration of an active analysis pipeline and is discarded upon
                            completion or session termination. Downloaded HTML reports exist solely on your local device.
                        </p>
                    </Section>

                    {/* Third Party */}
                    <Section title="6. Third-Party Services">
                        <p>Locus integrates with the following third-party services:</p>
                        <ul className="list-disc list-inside space-y-1.5 mt-3 text-slate-600">
                            <li><strong>Google Vertex AI</strong> — For multi-agent reasoning and natural language generation.</li>
                            <li><strong>Google Maps Platform</strong> — For geospatial visualization and place search.</li>
                            <li><strong>Google Search (via Grounding)</strong> — For real-time market intelligence retrieval.</li>
                        </ul>
                        <p className="mt-3">
                            Each of these services operates under its own privacy policy and terms. We encourage you to
                            review them independently.
                        </p>
                    </Section>

                    {/* Contact */}
                    <Section title="7. Contact">
                        <p>
                            For privacy-related inquiries, please contact the Intsemble team through{" "}
                            <a href="mailto:support@intsemble.com" className="text-indigo-600 underline hover:text-indigo-800">
                                support@intsemble.com
                            </a>.
                        </p>
                    </Section>
                </div>

                {/* Footer */}
                <div className="mt-12 pt-6 border-t border-slate-200 flex items-center justify-between text-xs text-slate-400">
                    <span>© {new Date().getFullYear()} Intsemble. All rights reserved.</span>
                    <Link href="/terms" className="hover:text-slate-600 transition-colors">
                        Terms of Service →
                    </Link>
                </div>
            </div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section className="backdrop-blur-sm bg-white/60 border border-slate-100/80 rounded-2xl p-6 shadow-sm">
            <h2 className="text-lg font-bold text-slate-800 mb-3">{title}</h2>
            <div className="text-sm text-slate-600 leading-relaxed space-y-3">{children}</div>
        </section>
    );
}
