"use client";

import Link from "next/link";

export default function TermsOfService() {
    return (
        <div className="min-h-screen relative z-10">
            <div className="max-w-3xl mx-auto px-6 py-12 lg:px-8">
                {/* Header */}
                <div className="mb-10">
                    <Link
                        href="/"
                        className="text-sm text-slate-500 hover:text-slate-700 transition-colors flex items-center gap-1.5 mb-6"
                    >
                        <span>←</span> Back to Locus
                    </Link>
                    <h1 className="text-4xl font-extrabold bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 to-cyan-500 mb-2">
                        Terms of Service
                    </h1>
                    <p className="text-slate-500 text-sm">
                        Last updated: March 7, 2026 · Effective immediately
                    </p>
                </div>

                <div className="space-y-8">
                    {/* Acceptance */}
                    <Section title="1. Acceptance of Terms">
                        <p>
                            By accessing or using Locus (&quot;the Platform&quot;), developed by <strong>Intsemble</strong>,
                            you agree to be bound by these Terms of Service. If you do not agree with any part of these
                            terms, you must discontinue use of the Platform immediately.
                        </p>
                    </Section>

                    {/* AI Disclaimer */}
                    <Section title="2. AI-Generated Content Disclaimer">
                        <div className="bg-amber-50/70 border border-amber-200 rounded-xl p-4 mb-4">
                            <p className="text-amber-900 text-sm font-medium mb-2">⚠️ Important Disclaimer</p>
                            <p className="text-amber-800 text-sm leading-relaxed">
                                All insights, recommendations, market analyses, competitor assessments, and strategic outputs
                                generated by Locus are <strong>probabilistic in nature</strong> and are produced by artificial
                                intelligence systems. These outputs should be treated as <strong>indicative guidance only</strong>,
                                not as definitive business, legal, financial, or real estate advice.
                            </p>
                        </div>
                        <p>
                            Intsemble and the Locus platform <strong>expressly disclaim all liability</strong> for any
                            capital-intensive decisions, investments, leases, property acquisitions, business launches,
                            or other financial commitments made in reliance upon Locus outputs. Users are solely
                            responsible for independently verifying all information and engaging qualified professionals
                            before making any business or investment decisions.
                        </p>
                    </Section>

                    {/* Google Maps */}
                    <Section title="3. Google Maps Platform Terms">
                        <div className="bg-blue-50/60 border border-blue-100 rounded-xl p-4 mb-4">
                            <p className="text-blue-800 text-sm font-medium mb-2">📍 Google Maps Terms</p>
                            <p className="text-blue-700 text-sm leading-relaxed">
                                Locus incorporates services from the Google Maps Platform. By using Locus, you are also
                                bound by the{" "}
                                <a
                                    href="https://maps.google.com/help/terms_maps/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="underline font-medium hover:text-blue-900"
                                >
                                    Google Maps/Google Earth Additional Terms of Service
                                </a>{" "}
                                and the{" "}
                                <a
                                    href="https://policies.google.com/privacy"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="underline font-medium hover:text-blue-900"
                                >
                                    Google Privacy Policy
                                </a>.
                            </p>
                        </div>
                        <p>
                            Map imagery, geospatial data, and place information are provided by Google and are subject
                            to Google&apos;s terms. You may not extract, scrape, or redistribute Google Maps data obtained
                            through Locus.
                        </p>
                    </Section>

                    {/* Use Restrictions */}
                    <Section title="4. Acceptable Use">
                        <p>You agree not to:</p>
                        <ul className="list-disc list-inside space-y-1.5 mt-3 text-slate-600">
                            <li>Use Locus outputs as the sole basis for high-value financial or real estate decisions.</li>
                            <li>Redistribute, resell, or commercially repackage Locus analysis reports without written consent.</li>
                            <li>Attempt to reverse-engineer, decompile, or extract the underlying agent architecture.</li>
                            <li>Submit queries that violate applicable laws, regulations, or third-party rights.</li>
                            <li>Use automated systems or bots to make bulk requests to the Platform.</li>
                        </ul>
                    </Section>

                    {/* No Warranty */}
                    <Section title="5. No Warranty">
                        <p>
                            Locus is provided <strong>&quot;as-is&quot;</strong> and <strong>&quot;as-available&quot;</strong> without
                            warranties of any kind, express or implied, including but not limited to implied
                            warranties of merchantability, fitness for a particular purpose, accuracy, or
                            non-infringement. Intsemble does not guarantee the completeness, reliability, or
                            timeliness of any data, analysis, or recommendation produced by the Platform.
                        </p>
                    </Section>

                    {/* Limitation */}
                    <Section title="6. Limitation of Liability">
                        <p>
                            In no event shall Intsemble, its officers, directors, employees, or agents be liable
                            for any indirect, incidental, special, consequential, or punitive damages arising from
                            your use of or inability to use the Platform, even if advised of the possibility of
                            such damages. Total liability shall not exceed the amount paid by you, if any, for
                            access to the Platform in the preceding twelve months.
                        </p>
                    </Section>

                    {/* IP */}
                    <Section title="7. Intellectual Property & Attribution">
                        <p>
                            The Locus platform, including its user interface, multi-agent pipeline architecture,
                            and proprietary prompt engineering, is the intellectual property of Intsemble.
                        </p>
                        <div className="bg-slate-50/80 border border-slate-200 rounded-xl p-4 mt-4">
                            <p className="text-slate-700 text-sm font-medium mb-2">📜 Open Source Attribution</p>
                            <p className="text-slate-600 text-sm leading-relaxed">
                                The foundational architectural patterns of the Locus multi-agent system are inspired by and
                                adapted from{" "}
                                <a
                                    href="https://github.com/google/adk-samples"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-indigo-600 underline font-medium hover:text-indigo-800"
                                >
                                    google/adk-samples
                                </a>
                                , made available under the{" "}
                                <a
                                    href="https://www.apache.org/licenses/LICENSE-2.0"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="text-indigo-600 underline font-medium hover:text-indigo-800"
                                >
                                    Apache License 2.0
                                </a>.
                                We acknowledge and credit the Google ADK team for the sample code and patterns that
                                informed the initial development of this platform.
                            </p>
                        </div>
                    </Section>

                    {/* Governing Law */}
                    <Section title="8. Governing Law">
                        <p>
                            These Terms shall be governed by and construed in accordance with the laws of India,
                            without regard to its conflict of law provisions. Any disputes arising under these Terms
                            shall be subject to the exclusive jurisdiction of the courts in Guwahati, Assam.
                        </p>
                    </Section>

                    {/* Modifications */}
                    <Section title="9. Modifications">
                        <p>
                            Intsemble reserves the right to modify these Terms at any time. Continued use of the
                            Platform constitutes acceptance of the revised terms. Material changes will be
                            communicated through the Platform interface.
                        </p>
                    </Section>
                </div>

                {/* Footer */}
                <div className="mt-12 pt-6 border-t border-slate-200 flex items-center justify-between text-xs text-slate-400">
                    <span>© {new Date().getFullYear()} Intsemble. All rights reserved.</span>
                    <Link href="/privacy" className="hover:text-slate-600 transition-colors">
                        Privacy Policy →
                    </Link>
                </div>
            </div>
        </div>
    );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
    return (
        <section className="backdrop-blur-sm bg-white/60 border border-slate-100/80 rounded-2xl p-6 shadow-sm">
            <h2 className="text-lg font-bold text-slate-800 mb-3">{title}</h2>
            <div className="text-sm text-slate-600 leading-relaxed space-y-3">{children}</div>
        </section>
    );
}
